AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
