#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["GOOGLE_CLOUD_PROJECT"] || abort("GOOGLE_CLOUD_PROJECT not set")
ENV["GOOGLE_CLOUD_REGION"] || abort("GOOGLE_CLOUD_REGION not set")
require "elelem"
Signal.trap("INT") { exit 1 }
Elelem.start(Net::Llm::VertexAI.new(model: "claude-sonnet-4@20250514"))
