#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["OPENAI_API_KEY"] || abort("OPENAI_API_KEY not set")
require "elelem"
Signal.trap("INT") { exit 1 }
Elelem.start(Net::Llm::OpenAI.new(model: "gpt-4"))
