#!/usr/bin/env ruby
# frozen_string_literal: true

require "elelem"

Signal.trap("INT") { exit 1 }

Elelem.start(Net::Llm::Claude.anthropic(
  model: "claude-sonnet-4-20250514",
  api_key: ENV.fetch("ANTHROPIC_API_KEY") { `pass api/console.anthropic.com/access-token | head -n1`.strip },
))
